[toolchain]
anchor_version = "0.29.0"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[programs.devnet]
calendarfi = "CalendarFiProgramIDPlaceholder"

[registry]
url = "https://api.github.com/repos/coral-xyz/anchor"

[build]
shell = "/bin/bash"

